line-length = 120
target-version = "py312"

[lint]
select = [
    #"ANN", # Flake8-annotations
    #"D",  # PyDocstyle
    "E",   # Pycodestyle errors
    "F",   # Pyflakes
    "W",   # Pywicked
    "B",   # Flake8-bugbear
    "C4",  # Flake8-comprehensions
    "I",   # Isort
    "N",   # PEP8-Naming
    "PGH", # Flake8-pygments
    "PTH", # Flake8-pytest-helper
    "Q",   # Flake8-quotes
    "RET", # Flake8-return
    "RUF", # Ruff-specific rules
    "SIM", # Flake8-simplify
    "UP",  # Flake8-pyupgrade
    "YTT", # Flake8-2020
]

ignore = [
    'F541',   # f-string without any placeholders
    'F841',   # Local variable is assigned to but never used
    'PTH123', # open() should be replaced by Path.open()
    'RET501', # Do not explicitly `return None` in function if it is the only possible return value
    'RET504', # Unnecessary assignment to variable before `return` statement
    'RET505', # Unnecessary `else` after `return` statement
    'SIM103', # Return the negated condition directly
    'E501',   # Line too long
]
